name: Android (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        cd armorpaint
        ../armorcore/make --target android --graphics opengl --compile
