name: iOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        cd armorpaint
        ../armorcore/make --target ios --graphics metal --compile
